---
apiVersion: eks.amazonaws.com/v1
kind: IngressClassParams
metadata:
  name: alb 
spec:
  scheme: internet-facing

---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: alb
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true" 
spec:
  controller: eks.amazonaws.com/alb
  parameters:
    apiGroup: eks.amazonaws.com
    kind: IngressClassParams
    name: alb 

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yopass-ingress
  namespace: yopass
  annotations:
        alb.ingress.kubernetes.io/certificate-arn: "{{ .Values.certificate_arn }}" 
spec:
  ingressClassName: alb 
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix 
            backend:
              service:
                name: yopass
                port:
                  number: 8082
